# .github/workflows/docker-image.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        id: vars
        run: |
          echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "EPOCH_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            aviel-job:${{ github.ref_name }}-${{ env.COMMIT_HASH }}-${{ env.EPOCH_TIMESTAMP }}
            aviel-service:${{ github.ref_name }}-${{ env.COMMIT_HASH }}-${{ env.EPOCH_TIMESTAMP }}
